### ISSUE TITLE
Missing character: There is no c in font nullfont!

### ISSUE THREAD

**Issue by nilesjohnson** [loopspace/braids#3]
There are some missing character warnings with the new tikz library.  I know they can be ignored, but they make it harder to find all the *other* problems with my tex documents :/

Example input:
```
\documentclass{minimal}

\usepackage{tikz}
\usetikzlibrary{
  braids,
  arrows.meta
}

\begin{document}

\begin{tikzpicture}[ultra thick]
\pic[
  rotate=90,
  braid/.cd,
  strand 1/.style={red},
  height=1cm,
  width=1cm,
] (braid) at (1,2) {braid={s_1 s_2}};
\end{tikzpicture}

\end{document}
```

Output snippet:
```
[Loading MPS to PDF converter (version 2006.09.02).]
) (/usr/share/texlive/texmf-dist/tex/latex/epstopdf-pkg/epstopdf-base.sty
(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))
Missing character: There is no c in font nullfont!
Missing character: There is no o in font nullfont!
Missing character: There is no d in font nullfont!
Missing character: There is no e in font nullfont!
Missing character: There is no = in font nullfont!
[1] (./braid_pic.aux) )
Output written on braid_pic.pdf (1 page, 1341 bytes).
```

**Comment by loopspace** [comment]
Hmm, thought I'd fixed this one - but maybe it was a similar bug in one of my other packages.

Is this with the latest CTAN release or with the latest from this repository?

**Comment by loopspace** [comment]
Possibly fixed in https://github.com/loopspace/braids/commit/57797339ad6ccc1bec0b20f97f450a1fd06a484f, or maybe another incantation of the same issue.

**Comment by nilesjohnson** [comment]
Oh, yeah this is whatever version is in texlive 2022; I should have tested with your latest update.  I'll report back here when I do that, and probably close this issue.

**Comment by nilesjohnson** [comment]
confirmed; the warnings do not appear when I use the newer version here!
